apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dotnet9424github-gitops
  description: This is GitOps manifest for dotnet9424github   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: dotnet9424github
    janus-idp.io/tekton: dotnet9424github
    backstage.io/kubernetes-id: dotnet9424github 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dotnet9424github
